POST http://localhost:3000/api/order
content-type: application/json

{
    "user": "test",
    "pass": "testp",
    "data":"123"
}
###
GET http://localhost:3000/api/order
content-type: application/json
Cookie: accessToken={{accessToken}}

{
    "user": "test",
    "pass": "testp",
    "data":"123"
}

###
POST http://localhost:3000/api/order
content-type: application/json
Cookie: accessToken={{accessToken}}

{
    "username": "testUser",
    "password": "testPass",
    "request": "testReq",
    "buyer": "testBuyer",
    "price": 25
}

###
PUT http://localhost:3000/api/order
content-type: application/json
Cookie: accessToken={{accessToken}}

{
    "order_id":1,
    "done_order":true
}

### 

GET http://localhost:3000/api/player
content-type: application/json
Cookie: accessToken={{accessToken}}

###
PUT http://localhost:3000/api/player
content-type: application/json
Cookie: accessToken={{accessToken}}

{
"discord_id":1,
"balance":"+2"
}